global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "broker"
    static_configs:
      - targets: ["broker:8080"]
    metrics_path: "/metrics"
    scheme: "http"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
